# baseurl = "https://www.pandamakes.com.au/html/shl_useapi/"
baseurl = "/"
languageCode = "en-us"
title = "SHL and Associates"
theme = "hugo-creative"
DefaultContentLanguage = "en"
googleAnalytics = ""

[languages]
	[languages.en]
		name = "SHL and Associates"
		[languages.en.params]

			name = "SHL and Associates"
			description = "At SHL & Associates Lawyers, we will protect your best interests. Lawyers you can trust!"

			favicon = "favicon.ico"


			# Navigation
			[languages.en.params.navigation]
				brand = "SHL and Associates"

				[languages.en.params.navigation.links]
					services  = "Areas of Practice"
					about     = "About"
					# portfolio = "Portfolio"
					contact   = "Contact"


			# Hero section
			[languages.en.params.hero]
				# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
				slogan     = "SHL and Associates"
				subtitle   = "At SHL & Associates Lawyers, we will protect your best interests."
				buttonText = "Lawyers you can trust!"


			# About section

			# Service section
			[languages.en.params.services]
				headline = "Areas of Practice "
				subtitle = "We offer legal services across various areas including commercial litigation, property law, conveyancing, commercial law, family law, criminal law, immigration law and notary public."

			[languages.en.params.about]
				headline    = "About SHL and Associates"
				description = "SHL & Associates Lawyers is a boutique law firm with a team of ethic, energetic, and enthusiastic of lawyers. <br /> <br /> At SHL & Associates Lawyers, we provide quality legal services tailored to your needs and objectives. We apply our expert knowledge and experience to deliver consistently high standards of legal services.    Whether it is a highly complex corporate dispute or a simple property transaction, we protect your best interests in an ethical, responsive and professional manner.  <br /><br />We are the lawyers whom you can trust."
				

				# Portfolio modals
			[languages.en.params.portfolio.modal]
				client = "Client"
				date = ""
				category = ""
				buttonText = "Close"

				# Aside section
			# [languages.en.params.aside]
			# 	headline = "Get the Creative Theme for Hugo"

			# 	[languages.en.params.aside.button]
			# 		text = "Download now"
			# 		link = "//github.com/digitalcraftsman/hugo-creative-theme"

			# Contact section
			[languages.en.params.contact]
				headline = "Contact us"
				description = "We would love to speak to you in confidence regarding your situation and needs."
				phone = " +61 2 8004 9826"
				fax = "+61 2 8004 9892"
				email = "jonathan.lu@shlandassociates.com.au"
				dx = "DX 258 Sydney"
				officeAddress = "Level 11, 84 Pitt Street, Sydney NSW 2000 Australia"
				postalAddress = "GPO Box 1636, Sydney NSW 2001"

[params]
	[params.location]
		latitude  = "-33.8668672"
		longitude = "151.208673"
		maps_api_key = "AIzaSyCTm3MsqzWr3B3_tueypyYBWbYtCDYtYPk"
		use_api = "true"